### ISSUE TITLE
Application closes when opening project as root 

### ISSUE THREAD

**Issue by kenfallon** [notklaatu/stopgo#40]
When running the application as root the application closes 

DEBUG: no target dir provided.

(stopgo:4194): Gtk-WARNING **: Could not find the icon 'dialog-information'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(stopgo:4194): Gtk-WARNING **: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita
Traceback (most recent call last):
  File "/tmp/.mount_fe17CJ/usr/share/pyshared/stopgolibs/gui.py", line 540, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_gdi.py", line 5130, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "IsOk()" failed at ./src/common/dcgraph.cpp(437) in SetTextBackground(): wxGCDC(cg)::SetTextBackground - invalid DC
Traceback (most recent call last):
  File "/tmp/.mount_fe17CJ/usr/share/pyshared/stopgolibs/gui.py", line 540, in OnPaint
    dc = wx.PaintDC(self)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_gdi.py", line 5130, in __init__
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(*args, **kwargs))
wx._core.PyAssertionError: C++ assertion "IsOk()" failed at ./src/common/dcgraph.cpp(437) in SetTextBackground(): wxGCDC(cg)::SetTextBackground - invalid DC

(stopgo:4194): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Trace/breakpoint trap

**Comment by notklaatu** [comment]
I confess I never thought to try launching this app as root. I'll look into this.
