### ISSUE TITLE
opening with the --shell option fails

### ISSUE THREAD

**Issue by kenfallon** [notklaatu/stopgo#42]
$ ./stopgo.AppImage --shell 
Starting StopGo...
Traceback (most recent call last):
  File "./bin//stopgo", line 64, in <module>
    app.getOptions()
  File "/tmp/.mount_guDViX/usr/share/pyshared/stopgolibs/app.py", line 47, in getOptions
    import shell
ImportError: No module named shell

**Comment by notklaatu** [comment]
I'm not sure what I intended with a --shell option, but it's bogus and will be removed.
