### ISSUE TITLE
Can't save images

### ISSUE THREAD

**Issue by kenfallon** [notklaatu/stopgo#45]
[00007f8ac4000978] core video output error: Failed to open '/home/ken/stopgo/stopgo_project_1484891218/images/001.png/vlcsnap-2017-01-20-07h21m58s416.png'
[00007f8ac4000978] core video output error: could not save snapshot
Traceback (most recent call last):
  File "/tmp/.mount_fRuxQb/usr/share/pyshared/stopgolibs/gui.py", line 196, in <lambda>
    self.Bind(wx.EVT_BUTTON, lambda event, args=(dbfile): self.CaptureCanvas(event,args), self.brec)
  File "/tmp/.mount_fRuxQb/usr/share/pyshared/stopgolibs/gui.py", line 589, in CaptureCanvas
    self.TakeSnapshot(e,args)
  File "/tmp/.mount_fRuxQb/usr/share/pyshared/stopgolibs/gui.py", line 602, in TakeSnapshot
    img = self.MakeThumbnail(os.path.join(self.imgdir, str(self.framlog).zfill(3)+'.png'), 100)
  File "/tmp/.mount_fRuxQb/usr/share/pyshared/stopgolibs/gui.py", line 465, in MakeThumbnail
    W = img.GetWidth()
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_core.py", line 3272, in GetWidth
    return _core_.Image_GetWidth(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "IsOk()" failed at ./src/common/image.cpp(1739) in GetWidth(): invalid image

**Comment by notklaatu** [comment]
Note to self: I'm pretty sure this is a bug in my AppImage MakeFile. Working on a fix.

**Comment by notklaatu** [comment]
Nope, this is a bug caused by the VLC version. I'll have to bundle VLC within the AppImage like god intended.
