### ISSUE TITLE
NameError: no function 'libvlc_new'

### ISSUE THREAD

**Issue by probonopd** [notklaatu/stopgo#49]
```
Starting StopGo...

Traceback (most recent call last):

  File "./bin//stopgo", line 64, in <module>

    app.getOptions()

  File "/run/firejail/appimage/.appimage-7968/usr/share/pyshared/stopgolibs/app.py", line 41, in getOptions

    gui.main(opts)

  File "/run/firejail/appimage/.appimage-7968/usr/share/pyshared/stopgolibs/gui.py", line 890, in main

    window = GUI(None, id=1, title="stopgo", style=wx.DEFAULT_FRAME_STYLE | wx.FULL_REPAINT_ON_RESIZE, clargs=opts)

  File "/run/firejail/appimage/.appimage-7968/usr/share/pyshared/stopgolibs/gui.py", line 40, in __init__

    self.InitUI()

  File "/run/firejail/appimage/.appimage-7968/usr/share/pyshared/stopgolibs/gui.py", line 139, in InitUI

    self.Instance = vlc.Instance()

  File "/run/firejail/appimage/.appimage-7968/usr/share/pyshared/stopgolibs/vlc.py", line 1551, in __new__

    return libvlc_new(len(args), args)

  File "/run/firejail/appimage/.appimage-7968/usr/share/pyshared/stopgolibs/vlc.py", line 4521, in libvlc_new

    ctypes.c_void_p, ctypes.c_int, ListPOINTER(ctypes.c_char_p))

  File "/run/firejail/appimage/.appimage-7968/usr/share/pyshared/stopgolibs/vlc.py", line 246, in _Cfunction

    raise NameError('no function %r' % (name,))

NameError: no function 'libvlc_new'
```

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266237653#L606-L624

**Comment by notklaatu** [comment]
Closing under the assumption that once I figure out the new AppImage structure, this error will be fixed.
