### ISSUE TITLE
Can't run windows version

### ISSUE THREAD

**Issue by arii-fae** [notklaatu/stopgo#54]
I have unzipped and installed all the pre-requisites, and i have the stop go application icon in my start menu, but when i run it (windows 10) i get:
```
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "usr\bin\stopgo", line 64, in <module>
  File "usr\share\pyshared\stopgolibs\app.py", line 40, in getOptions
  File "usr\share\pyshared\stopgolibs\gui.py", line 14, in <module>
  File "usr\share\pyshared\stopgolibs\vlc.py", line 176, in <module>
  File "usr\share\pyshared\stopgolibs\vlc.py", line 147, in find_lib
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application

---------------------------
OK   
---------------------------
```

**Comment by arii-fae** [comment]
I also tried installing the latest python (3.6.5) but it doesn't seem to change anything
